# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Yeast CRISPRi
tagline:          'Yeast CRISPRi'
description:      'Ingolia lab CRISPRi libraries for budding yeast'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Nicholas Ingolia'
  url:            https://ingolia-lab.org/

github:
  repo:           https://github.com/ingolia-lab/yeast-crispri